encoding: UTF-8
title: Josh Singley
description: Hobby maker and builder
url: joshsingley.com
author: Josh Singley
  picture: /img/joshsingley.jpg
  twitter: JoshSingley3
twitter:
  username:JoshSingley3
social:
  name: Josh Singley
  links:
    - https://twitter.com/JoshSingley3
    - https://www.instagram.com/josh_singley/
    - https://www.youtube.com/channel/UCZIPGdjm22_ekwKgijRmk7Q
lang: en_US
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
