encoding: UTF-8
name: Josh Singley
title: Josh Singley
description: Hobby maker and builder
url: joshsingley.com
author: Josh Singley
twitter: JoshSingley3
social:
  name: Josh Singley
  links:
    - https://twitter.com/JoshSingley3
    - https://www.instagram.com/josh_singley/
    - https://www.youtube.com/channel/UCZIPGdjm22_ekwKgijRmk7Q
lang: en_US
permalink: /blog/:year/:month/:day/:title/
url: http://joshsingley.com
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
collections:
    projects:
        output: true
        permalink: /:collection/:name